services:
  mongo:
    image: mongo:6
    ports: ["27018:27017"]   # keep separate from staging
    volumes: ["mongo-prod:/data/db"]
    restart: always

  backend:
    image: studymate-backend:${VERSION-DEV}
    environment:
      - MONGO_URL=mongodb://mongo:27017/studymate
      - NODE_ENV=production
      - PORT=5000
    depends_on: [mongo]
    ports: ["5002:5000"]
    restart: always
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 5

  frontend:
    image: studymate-frontend:${VERSION-DEV}
    environment:
      - REACT_APP_API=http://localhost:5002
    depends_on: [backend]
    ports: ["3002:3000"]
    restart: always
