version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"     # optional: expose only if you really need it
    volumes:
      - mongo-prod:/data/db
    networks:
      - studymate
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "127.0.0.1/test", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${BACKEND_IMAGE:-studymate-backend:DEV}
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://mongo:27017/studymate
      PORT: 5001
    ports:
      - "5001:5001"
    networks:
      - studymate

  frontend:
    image:  ${FRONTEND_IMAGE:-studymate-frontend:DEV}
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - studymate

networks:
  studymate:

volumes:
  mongo-prod:
